### ISSUE TITLE
png to dicom imageQuality

### ISSUE THREAD

**Issue by aysegulsayineker** [amine0110/convert-images-from-jpr-or-png-into-dicom#3]
Hello
when i try this code. Convert Png to Dicom there is a quality problem. 

input: 
![1-011](https://user-images.githubusercontent.com/93925759/206851537-b4ae94a9-a84c-4a10-bd47-e1fc5f3a1f68.png)

output : more dark
<img width="186" alt="image" src="https://user-images.githubusercontent.com/93925759/206851517-42486f46-129d-4138-84f4-914112d6c377.png">

**Comment by amine0110** [comment]
Hello

Hum I see. Sometimes, the array inside the dicom files contains values between -3000 and +3000 which controls the brightness of image. So I think in your case, since the image have values between 0 and 255 so it is not very bright (that what I think).

I think there are some parameters in the dicom files (like the max and min value), please check them while you are creating the dicom file (either in the dicom file that I provided or one of yours).

This is all that I know about this error! I hope that it helps.
